# Generated by Django 4.1.1 on 2022-09-19 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('Titulo', models.CharField(max_length=200)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('DemoLink', models.TextField(blank=True, max_length=2000, null=True)),
                ('SourceLink', models.TextField(blank=True, max_length=2000, null=True)),
                ('VotosTotal', models.IntegerField(blank=True, default=0, null=True)),
                ('VotosRatio', models.IntegerField(blank=True, default=0, null=True)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
