# Generated by Django 4.1.1 on 2022-09-19 20:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('Propietario', models.TextField(blank=True, null=True)),
                ('Body', models.TextField(blank=True, null=True)),
                ('Valor', models.CharField(choices=[('up', 'Voto Aprobado'), ('down', 'Voto Negado')], max_length=200)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('projecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto')),
            ],
        ),
    ]
