# Generated by Django 4.1.1 on 2022-09-19 21:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('Nombre', models.CharField(max_length=200)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('Id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
