# Generated by Django 4.1.1 on 2022-09-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='Tags',
            field=models.ManyToManyField(blank=True, to='projects.tag'),
        ),
    ]
