# Generated by Django 4.1.1 on 2022-09-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_proyecto_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='DemoLink',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='SourceLink',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
