# Generated by Django 4.1.1 on 2022-09-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_proyecto_demolink_alter_proyecto_sourcelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='ImagenDefecto',
            field=models.ImageField(blank=True, default='proyectos.png', null=True, upload_to=''),
        ),
    ]
